// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy9rOe2DOZk9Czv7tWgcZSRwRNLYEAzX8',
    appId: '1:648603478006:web:db6c075d0bc80b222b89d7',
    messagingSenderId: '648603478006',
    projectId: 'pikachu-63960',
    authDomain: 'pikachu-63960.firebaseapp.com',
    storageBucket: 'pikachu-63960.appspot.com',
    measurementId: 'G-7R0RTM9EG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AkG7oX45UvFX0KtZhl1SI79ZtGH15ck',
    appId: '1:648603478006:android:0434bfe0426752fe2b89d7',
    messagingSenderId: '648603478006',
    projectId: 'pikachu-63960',
    storageBucket: 'pikachu-63960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnUSFjLAirlxPlCaZMP3lXitO3AvXCtw',
    appId: '1:648603478006:ios:bda0019ef85b809b2b89d7',
    messagingSenderId: '648603478006',
    projectId: 'pikachu-63960',
    storageBucket: 'pikachu-63960.appspot.com',
    iosBundleId: 'com.example.pikachu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjnUSFjLAirlxPlCaZMP3lXitO3AvXCtw',
    appId: '1:648603478006:ios:bda0019ef85b809b2b89d7',
    messagingSenderId: '648603478006',
    projectId: 'pikachu-63960',
    storageBucket: 'pikachu-63960.appspot.com',
    iosBundleId: 'com.example.pikachu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy9rOe2DOZk9Czv7tWgcZSRwRNLYEAzX8',
    appId: '1:648603478006:web:b2d49f8cbdacba682b89d7',
    messagingSenderId: '648603478006',
    projectId: 'pikachu-63960',
    authDomain: 'pikachu-63960.firebaseapp.com',
    storageBucket: 'pikachu-63960.appspot.com',
    measurementId: 'G-PD29W60KJX',
  );

}